"use client";

import {
  createContext,
  useContext,
  useState,
  useCallback,
  type ReactNode,
} from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    about: "ABOUT",
    coalHauling: "COAL HAULING",
    ourTeam: "OUR TEAM",
    projects: "PROJECTS",
    news: "NEWS",
    learnMore: "Learn More",
    ourCommitment: "OUR COMMITMENT",
    toSustainability: "TO SUSTAINABILITY",
    heroTagline: "Let's energize Indonesia. Together.",
    search: "Search",
    aboutDesc: "The business of the Bayan Group is strongly built on the strength of our experience in Indonesia.",
    coalHaulingDesc: "Reliable coal transportation services with modern fleet and experienced team.",
    ourTeamDesc: "Our dedicated professionals committed to excellence and sustainable growth.",
    projectsDesc: "Explore our portfolio of completed and ongoing projects across Indonesia.",
    newsDesc: "Latest updates, press releases, and announcements from our company.",
    bataraOverview: "Batara Overview",
    visionMission: "Vision & Mission",
    fleet: "Our Fleet",
    operations: "Operations",
    services: "Services",
    leadership: "Leadership",
    departments: "Departments",
    careers: "Careers",
    usersExperience: "Users Experience",
    currentProjects: "Current Projects",
    completedProjects: "Completed Projects",
    pressReleases: "Press Releases",
    announcements: "Announcements",
    fromPresident: "From President Director",
    corporateStructure: "Corporate Structure",
    organization: "Organization",
    corporateGovernance: "Corporate Governance",
    awardsRecognition: "Awards & Recognition",
    contact: "Contact",
    // Our Unit / Fleet
    ourFleet: "Our Fleet",
    coreUnit: "The Core Unit",
    coreUnitDesc: "We use Prime Mover with Double Vessel configuration for heavy-duty coal hauling operations.",
    primeMoverDoubleVessel: "Prime Mover with Double Vessel",
    brand: "Brand",
    totalActiveUnits: "Total Active Units",
    supportUnit: "Support Unit",
    craneTruck: "Crane Truck",
    waterTruck: "Water Truck",
    fuelTruck: "Fuel Truck",
    telehandler: "Telehandler",
    excavator: "Excavator",
    mobilityUnit: "Mobility Unit",
    landVehicle: "Land Vehicle",
    busManhaul: "Bus Manhaul",
    operationsDesc: "Our coal hauling operations ensure efficient and reliable transportation from mine to port.",
    partnership: "Partnership",
    partnershipDesc: "Our company has a contract with Bayan Resource to haul their coal, providing reliable and efficient transportation services.",
    production: "Production",
    dailyProduction: "Actual Production per Day",
    ton: "ton",
    dailyProductionValue: "25,000 - 35,000 ton",
    yearlyProduction: "2025 Total Production",
    yearlyProductionValue: "4,575,815 ton",
    projectLocation: "Project Location",
    senyiur: "Senyiur",
    muaraPahu: "Muara Pahu",
    ongoing: "Ongoing",
    senyiurDesc: "Active coal hauling operations with Bayan Resource.",
    openProjects: "Open Projects",
    runsJuly2026: "Estimated run in July, 2026",
    operationRoute: "Operation Route",
    coalpadToWeightbridge: "Coal pad to Weightbridge",
    coalpadDistance: "70 - 80 km",
    weightbridgeToJetty: "Weightbridge to Jetty",
    jettyDistance: "± 5 km",
    projectLocationDesc: "Our projects with Bayan Resource across multiple locations.",
    routeDesc: "Average traveling distance for our coal hauling operations:",
    medicUnit: "Medic Unit",
    ambulance: "Ambulance",
    rescueCar: "Rescue Car",
    workforce: "Workforce",
    totalEmployees: "Total Employees",
    totalEmployeesValue: "300+",
    operators: "Operators",
    operatorsValue: "125+",
    // Leadership
    boardOfDirectors: "Board of Directors",
    commissary: "Commissioner",
    presidentDirector: "President Director",
    director: "Director",
    directorOperations: "Director of Operations",
    leadershipFocus: "Our focus is not merely to manage, but to guide the team toward shared goals, motivate, solve problems, and exemplify the behavior we expect.",
    leadershipTraits: "Key traits:",
    traitVision: "Accountable for vision & mission",
    traitStrategic: "Making strategic decisions",
    traitRoleModel: "Being a role model and motivator",
    traitCulture: "Developing company culture",
    // Managers
    managers: "Managers",
    managerOperation: "Manager Operation",
    managerPlant: "Manager Plant",
    managerHRGA: "Manager HRGA",
    managerFinance: "Manager Finance",
    managerAccounting: "Manager Accounting",
    managerInfrastructure: "Manager Infrastructure",
    managerProcurement: "Manager Procurement",
    // Site Senyiur PIC
    siteSenyiurPIC: "Site Senyiur — Person In Charge",
    indonesiaPratamaProject: "PT Indonesia Pratama Project",
    siteManager: "Site Manager",
    deputySite: "Deputy Site",
    deptHeadProduction: "Dept Head Production",
    deptHeadPlantLogistic: "Dept Head Plant & Logistic",
    deptHeadHSE: "Dept Head HSE",
    deptHeadInfrastructure: "Dept Head Infrastructure",
    deptHeadHRGA: "Dept Head HRGA",
    vacant: "Vacant",
    // Departments
    site: "Site",
    siteDepartment: "Site Department",
    headOffice: "Head Office",
    productionDept: "Production Dept",
    productionDeptFocus: "Production operations, output & quality",
    plantDept: "Plant Dept",
    plantDeptFocus: "Plant maintenance, equipment & facilities",
    hrgaDept: "HRGA Dept",
    hrgaDeptFocus: "Recruitment, training, work culture & general affairs",
    hseDept: "HSE Dept",
    hseDeptFocus: "Health, Safety & Environment",
    logisticDept: "Logistic Dept",
    logisticDeptFocus: "Logistics, material handling & transportation",
    operationDept: "Operation Dept",
    operationDeptFocus: "Operations coordination & monitoring",
    financeDept: "Finance Dept",
    financeDeptFocus: "Financial management & budgeting",
    accountingDept: "Accounting Dept",
    accountingDeptFocus: "Accounting & financial reporting",
    itDept: "IT Dept",
    itDeptFocus: "Technology & system development",
    procurementDept: "Procurement Dept",
    procurementDeptFocus: "Purchasing & procurement",
    infrastructureDept: "Infrastructure Dept",
    infrastructureDeptFocus: "Infrastructure & facility management",
    trainingCenterDept: "Training Center Dept",
    trainingCenterDeptFocus: "Employee training & development",
    mainFocus: "Main Focus",
    departmentLabel: "Department",
    // Organization
    organizationDesc: "At PT Batara Dharma Persada, organization means our complete structure — people, departments, work relationships, systems, and the goals we pursue in coal hauling excellence.",
    organizationDescBefore: "At ",
    organizationDescAfter: ", organization means our complete structure — people, departments, work relationships, systems, and the goals we pursue in coal hauling excellence.",
    organizationUmbrella: "This is the overarching framework that encompasses our leadership, site and head office departments, operations, and the internal culture that drives our partnership with Bayan Resource.",
    orgMainChars: "Key characteristics:",
    orgChar1: "Clear vision & mission for reliable coal logistics",
    orgChar2: "Structured hierarchy from Commissioner to operations",
    orgChar3: "Strong work systems & safety-focused culture",
    orgChar4: "Unified structure across Site and Head Office",
    orgExampleTitle: "PT Batara Dharma Persada — Our Organization:",
    orgExample: "Our organization spans from Commissioner to President Director, Directors, and 300+ dedicated employees across Production, Plant, HRGA, HSE, Logistics at Site, and Operations, Finance, IT, Procurement at Head Office — all working together to deliver efficient, safe coal hauling from mine to jetty.",
    vision: "Vision",
    visionPlaceholder: "Add your company vision here...",
    visionContent: "",
    mission: "Mission",
    missionPlaceholder: "Add your company mission here...",
    missionContent: "",
    coreValues: "Core Values",
    coreValuesPlaceholder: "Add your core values (e.g. Safety, Integrity, Excellence)...",
    coreValuesContent: "",
    addYourContent: "Your Content",
    addYourContentPlaceholder: "Add custom content — goals, milestones, or key messages...",
    addYourContentText: "",
    locations: "Locations",
    companyOverview: "Company Overview",
    templateCardsHint: "Template cards — add your content below",
    // Careers
    careersDesc: "Join our team and grow with PT Batara Dharma Persada. We are always looking for talented individuals to support our coal hauling operations.",
    careersDescBefore: "Join our team and grow with ",
    careersDescAfter: ". We are always looking for talented individuals to support our coal hauling operations.",
    whyJoinUs: "Why Join Us",
    whyJoinDesc: "Be part of a growing company with strong partnership, modern fleet, and commitment to safety and excellence.",
    howToApply: "How to Apply",
    checkPositionsFirst: "Please check the recruitment portal below for current open positions before applying.",
    howToApplyDesc: "Fill out our online recruitment form with your details and CV. We will review your application and contact you if there is a match.",
    sendCV: "Send Your CV",
    careersEmail: "hrga@bataradharmapersada.com",
    // Contact
    contactDesc: "Get in touch with us. We'd love to hear from you.",
    contactDescBefore: "Get in touch with ",
    contactDescAfter: ". We'd love to hear from you.",
    contactHeadOffice: "Head Office",
    contactAddress: "Address",
    contactAddressValue: "Rukan Grand Orchard Square, Jl. Terusan Klp. Hybrida Blok D22, Sukapura, Kec. Cilincing, Kota Adm, Daerah Khusus Ibukota Jakarta.",
    contactPhone: "Phone",
    contactPhoneValue: "+62 21 1234567",
    contactEmail: "Email",
    contactEmailValue: "info@bataramining.com",
    ctaTitle: "Ready to work with us?",
    ctaDesc: "Get in touch today and let's discuss how we can support your coal hauling needs.",
    ctaButton: "Contact Us",
    // STRIVE Core Values
    strive: "STRIVE",
    striveSubtitle: "Our core values that guide everything we do",
    striveS: "Synergy — A combined action from more than one participant to create cooperative action where the whole produces more than the sum of its parts.",
    striveT: "Trustworthy — Ability to behave honestly and with high commitment in accordance with company regulations and code of ethics consistently to maintain company reputation and customer satisfaction.",
    striveR: "Responsible — Taking ownership of our actions and obligations and always being creative and adaptable in finding solutions.",
    striveI: "Integrity — Having upstanding character traits and work ethics including sound judgement, honesty, dependability, and loyalty.",
    striveV: "Values — We have a set of guiding principles and fundamental beliefs that help the team work toward a common business goal. These values are often related to business relationships, customer relationships and company growth.",
    striveE: "Excellence — Sets a high standard, suggests excellence, and setting a positive example.",
  },
  id: {
    about: "TENTANG",
    coalHauling: "TRANSPORTASI BATUBARA",
    ourTeam: "TIM KAMI",
    projects: "PROYEK",
    news: "BERITA",
    learnMore: "Pelajari Lebih Lanjut",
    ourCommitment: "KOMITMEN KAMI",
    toSustainability: "UNTUK KEBERLANJUTAN",
    heroTagline: "Mari bersama-sama memberdayakan Indonesia.",
    search: "Cari",
    aboutDesc: "Bisnis Grup Bayan dibangun kuat berdasarkan pengalaman kami di Indonesia.",
    coalHaulingDesc: "Layanan transportasi batubara yang andal dengan armada modern dan tim berpengalaman.",
    ourTeamDesc: "Profesional kami yang berdedikasi untuk keunggulan dan pertumbuhan berkelanjutan.",
    projectsDesc: "Jelajahi portofolio proyek kami yang telah selesai dan sedang berjalan di Indonesia.",
    newsDesc: "Update terbaru, siaran pers, dan pengumuman dari perusahaan kami.",
    bataraOverview: "Gambaran Batara",
    visionMission: "Visi & Misi",
    fleet: "Armada Kami",
    operations: "Operasi",
    services: "Layanan",
    leadership: "Kepemimpinan",
    departments: "Departemen",
    careers: "Karir",
    usersExperience: "Pengalaman Pengguna",
    currentProjects: "Proyek Berjalan",
    completedProjects: "Proyek Selesai",
    pressReleases: "Siaran Pers",
    announcements: "Pengumuman",
    fromPresident: "Dari Direktur Utama",
    corporateStructure: "Struktur Perusahaan",
    organization: "Organisasi",
    corporateGovernance: "Tata Kelola Perusahaan",
    awardsRecognition: "Penghargaan & Pengakuan",
    contact: "Kontak",
    ourFleet: "Armada Kami",
    coreUnit: "Unit Inti",
    coreUnitDesc: "Kami menggunakan Prime Mover dengan konfigurasi Double Vessel untuk operasi angkutan batubara berat.",
    primeMoverDoubleVessel: "Prime Mover dengan Double Vessel",
    brand: "Merek",
    totalActiveUnits: "Total Unit Aktif",
    supportUnit: "Unit Pendukung",
    craneTruck: "Crane Truck",
    waterTruck: "Truk Air",
    fuelTruck: "Truk Bahan Bakar",
    telehandler: "Telehandler",
    excavator: "Excavator",
    mobilityUnit: "Unit Mobilitas",
    landVehicle: "Kendaraan Darat",
    busManhaul: "Bus Manhaul",
    operationsDesc: "Operasi angkutan batubara kami memastikan transportasi yang efisien dan andal dari tambang ke pelabuhan.",
    partnership: "Kemitraan",
    partnershipDesc: "Perusahaan kami memiliki kontrak dengan Bayan Resource untuk mengangkut batubara mereka, menyediakan layanan transportasi yang andal dan efisien.",
    production: "Produksi",
    dailyProduction: "Produksi Aktual per Hari",
    ton: "ton",
    dailyProductionValue: "25.000 - 35.000 ton",
    yearlyProduction: "Total Produksi 2025",
    yearlyProductionValue: "4.575.815 ton",
    projectLocation: "Lokasi Proyek",
    senyiur: "Senyiur",
    muaraPahu: "Muara Pahu",
    ongoing: "Berjalan",
    senyiurDesc: "Operasi angkutan batubara aktif dengan Bayan Resource.",
    openProjects: "Proyek Baru",
    runsJuly2026: "Estimasi beroperasi Juli 2026",
    operationRoute: "Rute Operasi",
    coalpadToWeightbridge: "Coal pad ke Weightbridge",
    coalpadDistance: "70 - 80 km",
    weightbridgeToJetty: "Weightbridge ke Jetty",
    jettyDistance: "± 5 km",
    projectLocationDesc: "Proyek kami dengan Bayan Resource di berbagai lokasi.",
    routeDesc: "Jarak tempuh rata-rata untuk operasi angkutan batubara kami:",
    medicUnit: "Unit Medis",
    ambulance: "Ambulans",
    rescueCar: "Mobil Rescue",
    workforce: "Tenaga Kerja",
    totalEmployees: "Total Karyawan",
    totalEmployeesValue: "300+",
    operators: "Operator",
    operatorsValue: "125+",
    // Leadership
    boardOfDirectors: "Dewan Direksi",
    commissary: "Komisaris",
    presidentDirector: "Direktur Utama",
    director: "Direktur",
    directorOperations: "Direktur Operasional",
    leadershipFocus: "Fokusnya bukan sekadar mengatur, tapi mengarahkan tim untuk mencapai tujuan bersama, memotivasi, memecahkan masalah, dan menjadi contoh perilaku yang diharapkan.",
    leadershipTraits: "Ciri-ciri:",
    traitVision: "Bertanggung jawab terhadap visi & misi",
    traitStrategic: "Memberi keputusan strategis",
    traitRoleModel: "Menjadi panutan dan motivator",
    traitCulture: "Mengembangkan budaya perusahaan",
    // Managers
    managers: "Manajer",
    managerOperation: "Manager Operasional",
    managerPlant: "Manager Plant",
    managerHRGA: "Manager HRGA",
    managerFinance: "Manager Keuangan",
    managerAccounting: "Manager Akuntansi",
    managerInfrastructure: "Manager Infrastruktur",
    managerProcurement: "Manager Pengadaan",
    // Site Senyiur PIC
    siteSenyiurPIC: "Site Senyiur — Person In Charge",
    indonesiaPratamaProject: "PT Indonesia Pratama Project",
    siteManager: "Site Manager",
    deputySite: "Wakil Site",
    deptHeadProduction: "Dept Head Produksi",
    deptHeadPlantLogistic: "Dept Head Plant & Logistik",
    deptHeadHSE: "Dept Head HSE",
    deptHeadInfrastructure: "Dept Head Infrastruktur",
    deptHeadHRGA: "Dept Head HRGA",
    vacant: "Lowong",
    // Departments
    site: "Site",
    siteDepartment: "Departemen Site",
    headOffice: "Kantor Pusat",
    productionDept: "Dept Produksi",
    productionDeptFocus: "Operasi produksi, output & kualitas",
    plantDept: "Dept Plant",
    plantDeptFocus: "Maintenance plant, peralatan & fasilitas",
    hrgaDept: "Dept HRGA",
    hrgaDeptFocus: "Rekrutmen, pelatihan, budaya kerja & umum",
    hseDept: "Dept HSE",
    hseDeptFocus: "Kesehatan, Keselamatan & Lingkungan",
    logisticDept: "Dept Logistik",
    logisticDeptFocus: "Logistik, penanganan material & transportasi",
    operationDept: "Dept Operasional",
    operationDeptFocus: "Koordinasi & pemantauan operasi",
    financeDept: "Dept Keuangan",
    financeDeptFocus: "Manajemen keuangan & penganggaran",
    accountingDept: "Dept Akuntansi",
    accountingDeptFocus: "Akuntansi & laporan keuangan",
    itDept: "Dept IT",
    itDeptFocus: "Pengembangan teknologi & sistem",
    procurementDept: "Dept Procurement",
    procurementDeptFocus: "Pembelian & pengadaan",
    infrastructureDept: "Dept Infrastruktur",
    infrastructureDeptFocus: "Manajemen infrastruktur & fasilitas",
    trainingCenterDept: "Dept Training Center",
    trainingCenterDeptFocus: "Pelatihan & pengembangan karyawan",
    mainFocus: "Fokus Utama",
    departmentLabel: "Departemen",
    // Organization
    organizationDesc: "Di PT Batara Dharma Persada, organisasi artinya keseluruhan struktur kami — orang, departemen, hubungan kerja, sistem, dan tujuan dalam keunggulan angkutan batubara.",
    organizationDescBefore: "Di ",
    organizationDescAfter: ", organisasi artinya keseluruhan struktur kami — orang, departemen, hubungan kerja, sistem, dan tujuan dalam keunggulan angkutan batubara.",
    organizationUmbrella: "Ini adalah payung besar yang mencakup kepemimpinan, departemen site dan kantor pusat, operasi, serta budaya internal yang mendorong kemitraan kami dengan Bayan Resource.",
    orgMainChars: "Karakter utama:",
    orgChar1: "Visi & misi yang jelas untuk logistik batubara andal",
    orgChar2: "Struktur hierarki dari Komisaris hingga operasional",
    orgChar3: "Sistem kerja & budaya berorientasi keselamatan",
    orgChar4: "Struktur terpadu di Site dan Kantor Pusat",
    orgExampleTitle: "PT Batara Dharma Persada — Organisasi Kami:",
    orgExample: "Organisasi kami mencakup dari Komisaris, Direktur Utama, Direktur, hingga 300+ karyawan di Production, Plant, HRGA, HSE, Logistics di Site, serta Operations, Finance, IT, Procurement di Kantor Pusat — semua bekerja bersama menyediakan angkutan batubara yang efisien dan aman dari tambang ke jetty.",
    vision: "Visi",
    visionPlaceholder: "Tambahkan visi perusahaan Anda di sini...",
    visionContent: "",
    mission: "Misi",
    missionPlaceholder: "Tambahkan misi perusahaan Anda di sini...",
    missionContent: "",
    coreValues: "Nilai Inti",
    coreValuesPlaceholder: "Tambahkan nilai inti (mis. Keselamatan, Integritas, Keunggulan)...",
    coreValuesContent: "",
    addYourContent: "Konten Anda",
    addYourContentPlaceholder: "Tambahkan konten kustom — tujuan, pencapaian, atau pesan utama...",
    addYourContentText: "",
    locations: "Lokasi",
    companyOverview: "Gambaran Perusahaan",
    templateCardsHint: "Kartu template — tambahkan konten Anda di bawah",
    // Careers
    careersDesc: "Bergabung dengan tim kami dan berkembang bersama PT Batara Dharma Persada. Kami selalu mencari individu berbakat untuk mendukung operasi angkutan batubara kami.",
    careersDescBefore: "Bergabung dengan tim kami dan berkembang bersama ",
    careersDescAfter: ". Kami selalu mencari individu berbakat untuk mendukung operasi angkutan batubara kami.",
    whyJoinUs: "Mengapa Bergabung",
    whyJoinDesc: "Jadilah bagian dari perusahaan yang berkembang dengan kemitraan kuat, armada modern, dan komitmen pada keselamatan serta keunggulan.",
    howToApply: "Cara Melamar",
    checkPositionsFirst: "Silakan cek portal rekrutmen di bawah untuk posisi yang saat ini terbuka sebelum melamar.",
    howToApplyDesc: "Isi formulir rekrutmen online kami dengan detail dan CV Anda. Kami akan meninjau lamaran dan menghubungi jika sesuai.",
    sendCV: "Kirim CV Anda",
    careersEmail: "hrga@bataradharmapersada.com",
    // Contact
    contactDesc: "Hubungi kami. Kami ingin mendengar dari Anda.",
    contactDescBefore: "Hubungi ",
    contactDescAfter: ". Kami ingin mendengar dari Anda.",
    contactHeadOffice: "Kantor Pusat",
    contactAddress: "Alamat",
    contactAddressValue: "Rukan Grand Orchard Square, Jl. Terusan Klp. Hybrida Blok D22, Sukapura, Kec. Cilincing, Kota Adm, Daerah Khusus Ibukota Jakarta.",
    contactPhone: "Telepon",
    contactPhoneValue: "+62 21 1234567",
    contactEmail: "Email",
    contactEmailValue: "info@bataramining.com",
    ctaTitle: "Siap bekerja sama dengan kami?",
    ctaDesc: "Hubungi kami hari ini dan mari diskusikan bagaimana kami dapat mendukung kebutuhan angkutan batubara Anda.",
    ctaButton: "Hubungi Kami",
    // STRIVE Core Values
    strive: "STRIVE",
    striveSubtitle: "Nilai inti kami yang memandu semua yang kami lakukan",
    striveS: "Synergy — Aksi gabungan dari lebih dari satu pihak untuk menciptakan aksi kooperatif di mana keseluruhan menghasilkan lebih dari jumlah bagian-bagiannya.",
    striveT: "Trustworthy — Kemampuan bersikap jujur dan berkomitmen tinggi sesuai regulasi perusahaan dan kode etik secara konsisten untuk menjaga reputasi perusahaan dan kepuasan pelanggan.",
    striveR: "Responsible — Mengambil kepemilikan atas tindakan dan kewajiban kami serta selalu kreatif dan adaptif dalam mencari solusi.",
    striveI: "Integrity — Memiliki karakter dan etika kerja yang terpuji termasuk pertimbangan yang baik, kejujuran, keandalan, dan loyalitas.",
    striveV: "Values — Kami memiliki prinsip panduan dan keyakinan fundamental yang membantu tim bekerja menuju tujuan bisnis bersama. Nilai-nilai ini sering terkait dengan hubungan bisnis, hubungan pelanggan, dan pertumbuhan perusahaan.",
    striveE: "Excellence — Menetapkan standar tinggi, menyarankan keunggulan, dan menjadi contoh positif.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback(
    (key: string) => {
      return translations[language][key] ?? translations.en[key] ?? key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
